### ISSUE TITLE
Error: Cannot find module 'cheerio' using create-react-app and webpack

### ISSUE THREAD

**Issue by NightlySide** [talmobi/yt-search#36]
Using create-react-app, webpack and the default config as well as the following code : 
```js
import YTSearch from "yt-search";

async function debug() {
    console.dir(await YTSearch("some video"));
}

debug();
```

I got the following error : **Error: Cannot find module 'cheerio'** with the stack:
```
Uncaught Error: Cannot find module 'cheerio'
    s yt-search.min.js:1
    s yt-search.min.js:1
    ./node_modules/yt-search/dist/yt-search.min.js/</<[1]< yt-search.min.js:1
    s yt-search.min.js:1
    r yt-search.min.js:1
    js yt-search.min.js:1
    js yt-search.min.js:1
    js yt-search.min.js:1
    Webpack 15
yt-search.min.js:1
```

Any idea how to fix that issue? I'm using typescript but the issue is style present with vanilla javascript.

**Comment by talmobi** [comment]
Hello,

Are you trying to use it in browser/client/frontend side code? create-react-app is usually created to serve browser/client/frontend side applications.

`yt-search` should only work if you run it on the server side (within `node` directly). The reason for this is because you generally cannot make http requests to third-party sites (such as youtube) through popular modern browsers (Chrome, Firefox, Safari etc). The reason you can't is because all popular browsers (Chrome, Firefox, Safari, etc) prevents such behaviour (CORS policy). The reason they prevent this, is because it is easily abused (which is bad both for the users and for third-party websites, essentially bad for the internet in general).

You can get around this by hosting a server that would do those requests for you through some kind of API that you would then use on your website.

**Comment by talmobi** [comment]
See example here:

http://yt-search-api-example.jin.fi/api/superman+theme

source code: https://github.com/talmobi/yt-search-api-example/blob/master/server.js

**Comment by NightlySide** [comment]
Thank you for your response. Yes actually I'm running yt-search on the client side and with a simple electron + typescript it works perfectly!
I manage to find a workaround. Instead of packaging the whole project with webpack i'm now just compiling my typescript files and it works.
I didn't know the CORS policy had a thing to do with the fact that the cheerio module couldn't be found by webpack :/

**Comment by talmobi** [comment]
CORS shouldn't have anything to do with npm modules or webpack.

Also Electron should be able to bypass any CORS restrictions because it's not a normal browser (normal browsers generally visit websites on the internet exclusively). That is, you should probably be able to turn off the CORS restriction within your Electron app.

That being said, I'm not entirely sure what was wrong with your setup or if it was an issue with `yt-search` itself. But it looked like you were trying to use it within a browser context that didn't have access to node_modules.

Webpack, like any bundler, typically just gathers all the code/local dependencies in one single file. It's generally used/recommended for client side code. Although commonly also used for transpiling server side code as well.

But glad you got it working.

**Comment by NightlySide** [comment]
Thanks actually it was my mistake mixing electron and webpack. It did the same thing with other packages because, like yt-search, they were not made for running in the browser but on the main node process.

Thank you for your amazing support!

**Comment by talmobi** [comment]
@NightlySide Thanks for the update~
