### ISSUE TITLE
Not showing all videos

### ISSUE THREAD

**Issue by YEETINGCHUBBUM** [talmobi/yt-search#37]
I am not sure whether this was a built in limitation, but I can only see 17-20 videos from one search, even when I print the whole list. Is this a mistake, or was this intentional?
![image](https://user-images.githubusercontent.com/73912694/100808854-ea468080-3402-11eb-950d-0eefc01f9b80.png)
![image](https://user-images.githubusercontent.com/73912694/100809100-68a32280-3403-11eb-9976-70f7bcd0b8c6.png)

**Comment by talmobi** [comment]
It's not precisely intentional, it's just the first page results that youtube provides from the initial http request.

I have thought about supporting getting more results indefinitely and at one point had something working but have decided against developing it further for now. The reason is I want to keep it simple and basically work as a proxy for a simple youtube search. Also YouTube provides its own API if you want full control, although I think it costs a bit of money.

Also, I think https://github.com/TimeForANinja/node-ytsr supports getting additional/next page results as well as some filtering support (e.g. searching by length and date).

Filtering support may be added to `yt-search` at some point (same things you can control on a simple youtube page search). Next/more page results isn't on the road plan as of yet. This isn't really intended for bulk crawling. node-ytsr or YouTubes own API may be better for those kinds of use cases.
