### ISSUE TITLE
Callback is not a function (Discord.js)

### ISSUE THREAD

**Issue by davvidlee** [talmobi/yt-search#38]
When I run this code, I get an error saying "TypeError: callback is not a function" on "callback(err);". I'm not sure if it is a problem with my code or yt-search, but I got my code straight from a YouTube video and there weren't any people complaining.

[code.txt](https://github.com/talmobi/yt-search/files/5646771/code.txt)

**Comment by talmobi** [comment]
If you're not using `await` you have to provide a callback function to get access to the results (standard node callback convention).

The standard node callback convention is a callback with the first argument being a potential error, and the rest/other arguments (if any) being results.

example:
```
const yts = require( 'yt-search' )
yts( 'superman theme', function ( err, result ) {
  if ( err ) throw err
  console.log( result.videos[ 0 ].title )
} )
```

The code you linked to seems to require `yt-search` twice for some reason [1] and also uses the API with wrong arguments here:

`        let results = await search(query.first().content, opts)`

The opts object's fields are also unsupported:

```
const opts = {
    maxResults: 10,
    key: config.YOUTUBE_API,
    type: 'video'
};
```

It looks like it is trying to use the API of https://github.com/TimeForANinja/node-ytsr instead of `yt-search`. This indicates that perhaps both `node-ytsr` and `yt-search` was being tested and required [1] at some point instead of requiring `yt-search` twice.

For a `yt-search` compatible call, it it should be something like this:

```
let result = await yts( query.first().content )
console.log( result.videos ) // list of videos
```

The rest of the result parsing also has to be changed to match the result object returned by `yt-search`.

**Comment by talmobi** [comment]
@davvidlee Also can you link the video you got the code from?

**Comment by davvidlee** [comment]
https://www.youtube.com/watch?v=QCWhmN1Qcjw

This is the youtube video. Also, I'm pretty new to coding in Javascript, so sorry if I'm making a lot of mistakes in my code. Thanks!

**Comment by davvidlee** [comment]
Hey @talmobi, I watched the video again, and I realized that I was using the wrong API this whole time. I watched a lot of different videos on how to make a Discord Music Bot that searches through Youtube, and I must've gotten confused on all the different API's they used. Sorry for the confusion!

**Comment by talmobi** [comment]
That video is referencing a completely different library called `youtube-search` which talks to the official YouTube API and needs an API key.

`yt-search` (this library) is a completely separate library. That parses a simple youtube search just like any normal user would do on the webpage. You do not need an API key for this.
