### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by SoEpik** [talmobi/yt-search#44]
This seems to be something to do with Thumbnails

Code:

Example > id = "PL67B0C9D86F829544"

`const list = await yts( { listId: id } )   `

Error:

` at node_modules\yt-search\dist\yt-search.js:850:69`

**Comment by SoEpik** [comment]
![image](https://user-images.githubusercontent.com/52017098/107016696-e0732d80-6763-11eb-8c2c-b899aa75e0e5.png)

Ended up bypassing it myself in the mean time

**Comment by SoEpik** [comment]
![image](https://user-images.githubusercontent.com/52017098/107019006-c555ed00-6766-11eb-9be2-68671ff2a062.png)
Also only gets 101 out of 151 from the playlist

**Comment by talmobi** [comment]
Hello there,

This has been fixed in the latest patch `2.6.2` and also in the latest feat release `2.7.0`. It no longer crashes and parses as much as it can.

The `views` is also fixed instead of being 1 when it should be more than a million.

in `2.7.0` a `size` field is added to the playlist metadata result that should show the amount of videos in the playlist (151 in this case), however the videos array is capped at 100 at the moment. This is because the initial request only populates the first 100 videos and the rest require further http requests (scrolling down in the browser for example).

I'm not yet sure how or if this library wants to handle such cases. Is getting all the video details for large playlists important for your use-case?

**Comment by SoEpik** [comment]
I am using this api for a Discord bot so being able to request one whole array would be helpful. Unless there would be a way to request the rest if they are in another array. Thank you for the help

**Comment by talmobi** [comment]
Currently this library does not, but this one might: https://www.npmjs.com/package/ytsr

**Comment by SoEpik** [comment]
just moved over thank you
