### ISSUE TITLE
Causing program to lag (_parseSearchResultInitialData)

### ISSUE THREAD

**Issue by PanicIsReal** [talmobi/yt-search#73]
Hi,

I recently switched over to this api as it was giving me much more accurate results based on search phrasing (rather than using direct URLs).

But every time I search for a video it pauses my program for a noticeable second. I ran the profiler and it seems to be from parsing the html data?

![image](https://github.com/talmobi/yt-search/assets/3466546/b93d1e69-3f7d-4865-aebd-ee198efd9f88)

If you look it shows _parseSearchResultInitialData taking almost 1 second to run. I have a private discord bot that plays music and every time a song is queued and this library does its thing it causes the current song playing over the bot to pauses its jarring and very noticeable. Is there any way to optimize this function better?

This is how it is being called:
```
async getStream(queryOrUrl: string): Promise<[Readable, SongEntry]> {
        let song: SongEntry = {};
    
        try {
            let searchResults = await yts(queryOrUrl);
            if (searchResults.all.length > 0) {
                const firstVideo = searchResults.all[0] as VideoSearchResult
                song = {
                    url: firstVideo.url,
                    title: firstVideo.title!,
                    length: firstVideo.timestamp
                }
                const stream = ytdl(song.url!, { 
                    filter: 'audioonly',
                    highWaterMark: 1 << 25
                });
        
                return [stream, song];
            } else {
                throw new Error("No results found");
            }
        } catch (error) {
            console.error("Search error:", error);
            throw error;
        }
    }
```

**Comment by talmobi** [comment]
@PanicIsReal hello,

In theory it should be possible but it involves complicated steps. The JSON.parse itself takes ~300ms and the corresponding JSON investigations (using `jsonpath-plus` https://github.com/JSONPath-Plus/JSONPath) takes the most of the rest of the time. It would be possible to stagger the jsonpath-plus queries to help with this, but staggering JSON.parse itself is tricker but doable.

It seems to me a lot of gimmicky/complex workarounds instead of just running the work in another thread. Because blocking music for even 30ms will probably be noticeable. I'm not sure why your music playing is blocking -- is it running on the very same thread/node process or just on the same box?

I would try and run the music playing in another thread/node process with higher priority instead. Is it streaming the music as sound to a discord voice channel which is why it's causing jittering?

**Comment by PanicIsReal** [comment]
Good suggestion, right now the music plays using Discord.js’ built in command AudioResource and AudioPlayer.play, I’m not sure how they’re programmed internally but a temp work around I’ve done is to move the YouTube query into a worker thread which has pretty much solved the issue. But you’ve peaked my interest with moving the audio stream to another worker but again I’m not sure if this is doable since it’s built in to the framework. Something to look in to.

**Comment by talmobi** [comment]
@PanicIsReal sounds like a fine solution the main idea splitting the two into separate threads/workers.

**Comment by PanicIsReal** [comment]
I will mark this as closed now, simply moving the search to a worker resolved any lag in the main thread. Thanks!
