### ISSUE TITLE
Issue with videoCount & videoCountLabel

### ISSUE THREAD

**Issue by SpaceGaint** [talmobi/yt-search#75]
Both the values of key videoCount and videoCountLabel are returning -1 instead of correct video count. Hoping for a fix asap.

It would be also better to add these metadata for videos:
- like
- comments
- viewsLabel

Also metadata for channels:
- channel description
- joined date
- country
- average views
- links ( 👈👆 these all from about channel section )
- playlists count and countLabel
- community posts count and countLabel ( search community posts and returns metadata of it )

**Comment by talmobi** [comment]
@SpaceGaint hello -- last time we investigated it looked like YouTube had disabled video count, see https://github.com/talmobi/yt-search/issues/71

- views should already be available -- maybe you mean something different with viewLabel I'm not sure?
- likes are now hidden by YouTube so that isn't available, I think
- comments are not available in the initial page load information (in the embedded ytInitialData javascript object) and seems to be loaded dynamically after page load -- this would require the use of something like puppeteer and is out of scope for this library in my opinion (better to make or use a specific library to fetch a YouTube videos comments in a smart way)

some of your other suggestions might be possible -- I haven't looked at what the latest ytInitialData object has in it -- I don't have the time to look into it at the moment -- if you have the time a PR would be appreciated -- basically it looks like YouTube returns a pre-rendered html file that includes initial data in the form of a global 'ytInitialData' object that the YouTube's internal rendering code will use to render the information on screen -- this library uses that object to parse information into a more usable form -- YouTube has gone through a few different ways they do this but this seems to still be valid

this library is intended to give the same information as you would get when you as a normal user would browse on YouTube -- insofar only what is available on the initial page load for simplicity

if you need something more professional I suggest the official YouTube API 🙇
